language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"


cache:
  directories:
  - libs

os:
  - linux

# For linux systems
addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev

install: "make init"

# command to run tests
script:
    - BIN_DIR=./bin make test HYPOTHESIS_PROFILE=ci
