language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libbz2-dev liblzma-dev

install: "make init"

# command to run tests
script:
    - make test HYPOTHESIS_PROFILE=ci
