os: linux
language: python
cache:
  directories:
  - ".cache"
python:
  - '3.6'
  - '3.7'
  - '3.8'
before_install:
  - source scripts/bootstrap
script:
  make ci HYPOTHESIS_PROFILE=ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
jobs:
  include:
  - stage: Deploy to pypi
    python: '3.6'
    script: skip
    deploy:
      provider: pypi
      user: wkretzsch
      password: $PYPI_PASSWORD
      server: https://test.pypi.org/legacy/
      on:
        tags: true
