language: python
python:
- '3.6'
cache:
  directories:
  - ".cache"
  - libs
os:
- linux
addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev
install:
- make init
after_success:
- codecov
- codecov --token='6b85102c-c69a-4b95-8ddc-4325d01b4c9f'
- make lint
jobs:
  include:
  - stage: Tests
    script: make ci HYPOTHESIS_PROFILE=ci
  - stage: Deploy to pypi
    python: '3.6'
    script: skip
    deploy:
      provider: pypi
      user: wkretzsch
      password:
        secure: "J0SC3ABsFWunUi5KAMw9OOQ67HjW2hHvs6wtphfJ4JV2RMHlQa5Z9tRsgdksKTJv3tF/Ct3zZyi4qbyeIUOPrktQTIjYwUeq36jnjDZ3/Uo3F+T1/g+dGYhVuAfsYEH7yZhnGD+PPyaNPGgYPksCdvQEV+5Zu2l7DC0hAJZtBxtX39PEDEy0A7D7k2SKhsvQIeEMaVex6vpQCI3/Zrs7Do+Hq2vh5GkjeOooDMYBuGPTbgP4JGDaKU/KG4nMsPwFmmrGrFzE8ljeqA9BqaCu9j9M09tkdvKr3PW5jCfUO3Rbof/Ejp6gh3LOcKsN7zvTl97tcURYT6KtXfdTNrEwV7eaI+u/vTLcZLrig2yGAfviFvqX4VI2fpLgulGQ3dp3hDkMUJavNvN6uDK5n+CyWXWqBGMT99CB8yKifPqGGQLidGnxwOBMtdfY/Xl0D7naoUwYJycESVsxsqAQr5zVNThu8qXIcuz1/615lDkn7/a477pSacBa9JcBNMIYlw6FheQjrt1mTx1jG4ypMy8VWLdGXhqeXWylqHJ1PDIoIaGZoqQkYSKrVrXuvLrZiK7WYKyfKPnka87UUYJHNzTtZNv7Ee3rH1TWHJAkJlyqotCG6zOykHAbgW2eYV0rSgNQBK0YFmj6dhqRvOsKSoXMxTXaLnwCTFtc0kO+ZqUUNl0="
      server: https://test.pypi.org/legacy/
      on:
        tags: true
