language: python
python:
- '3.6'
cache:
  directories:
  - ".cache"
  - libs
os:
- linux
addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev
install:
- make init
after_success:
- codecov
- codecov --token='6b85102c-c69a-4b95-8ddc-4325d01b4c9f'
- make lint
jobs:
  include:
  - stage: Tests
    script: make ci HYPOTHESIS_PROFILE=ci
  - stage: Deploy to pypi
    python: '3.6'
    script: skip
    deploy:
      provider: pypi
      user: wkretzsch
      password:
        secure: lt1qlccGfTVaaKMwVfB0T95FUtV+T0XlZjr7UXL/IaCQ6PgllYskcg/RJ60WP7wRe9VxNgxxsnYFJqjowgYNIebEIFQ5k19O414voSIJiu2XYyG5FqNQLBg9CBdVPobZtNMH4I80aKaKjngUMzPyRvS1t04kNkVgu+rRwgVRcnO+N5w4CzXm9WDC21FelOvbxLGp2xuuaddd1ilCmiv1iXTd+a+noHNXZ8SwZMDu/0jT6zOCcZuQK5Dj0qH1gGk70uoTQCHE7n41U5qx/51UmJP5R0pTquyfR0ofXIO4Wsnd7wg/9a2DSsGSXduFWI205p3pGWbnrJSkhD5FzoB1/ThM9d2CrozXJi20KTlVY/11F0X9ezFy9vZ9GSshlOQ3/ajD39Zcg/ZfhtoAcgVSkQTifYD2LVgRSV/Ga8csBsOjsx2Rs2Kd1Xi5Y1wWHZN+3DQ/SOTvF66aYzqU8joHqLOnYIlz0HpgSvgy2TRNfLQcwzASsv3jA4fI7ctm3EiQc6eh0JBtNN9TPsNJIbtdssCRcyDd/dR05DIc0wkRgdl10H18QhSOVrsnz+s7wa8Iq3F9YI1NfUw2Lthe260wGUZSD9t1NlaPFmqqtLBDlZ5okjguF9ZjCVglrOtBp77IP1YQTOLySSBR2TX8mRUB1pwf2i0pgNribxMFTJLafeU=
      server: https://test.pypi.org/legacy/
      on:
        tags: true
