language: python
python:
- '3.5'
- '3.6'
cache:
  directories:
  - ".cache"
  - libs
os:
- linux
addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev
install: make init
script: BIN_DIR=./bin make test HYPOTHESIS_PROFILE=ci
after_success:
- make lint
- coveralls
jobs:
  include:
  - stage: deploy to pypi
    python: '3.6'
    script: skip
    deploy:
      provider: pypi
      user: wkretzsch
      password:
        secure: yaVRwoyjgnV8YayZW0nz743kNG7RRh/g74FZjB7nGsbUn8nWapYDphgppaiiuFLX9n7R9cTpiXghBZIXs6yMQRqBgUJa/xZE4T/yuHK+mptIOrNeBSTE16PSwdRqlFUVPs/C3LMQkEPERjUaSOjfj1iqW2BxLb8MUC1RgK2akoJOWUrZVd1HWPtlJXnJ7dWd0vkA3pYoyGO2IpZVywtWq2GjAREUY3rEKV1vpCku+prZeLZyuqcGVkFYO3YpJqfBavG1IwntgBiyDwrj69NlwRDhgc9hjUOMigQWEjQCo4t7AH75sN8a5AhyQowyO3xPLRjN56hbqKIkW5wkeKK+laL5Oip1JdwjgNxfb8fBgKcD6fbuHTZvpOVqlk/koJ40MXf5eIQpPhYKEsZmLWujldTrfbZk1m4msHo3SOx382UiJ1rp04UqVK4PDRqDsGMhhSt2TIwd64fGlJ9zbZ7QEcKB7gk5zyi8aQg9Fo7ozE58pDlV2nvySH8J5CrkQW246sqUNTU6EKXzvNW22Yzy2+ULGPVJEBrLnFlp4oUnh71aviYDksXTWtS+0qcnEcCQud2WWE+xCe9G5F8uSV417s5/iJN8vG3vKXLZm3uUR9+z0c/fxTWcFaL+/Oq0HHO/ifWCuhAgI3kEIIt3L2cDpTACwjSBZJMwCHQoMYBEVn8=
      server: https://test.pypi.org/legacy/
      on:
        tags: true

  - stage: benchmark
    python: '3.6'
    if: tag =~ ^\d
    script: make benchmark
