language: python
python:
- '3.5'
- '3.6'
cache:
  directories:
  - ".cache"
  - libs
os:
- linux
addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev
install: make init
script: BIN_DIR=./bin make test HYPOTHESIS_PROFILE=ci
after_success:
- make lint
- coveralls
jobs:
  include:
  - stage: deploy to testpypi
    python: '3.6'
    deploy:
      provider: pypitest
      user: wkretzsch
      password:
        secure: JlF4Jgihr49i+Eee0tQTSAoTzWwUU+2c8fWphwmDN+O3SW03aPINJydudozlfVNK/Rptejm0FdqkEmRpNzR8zFIwI431laqlQSuYhso4MGRLRq0vEN4APHYxr7o2MciXQFqQ4cAH4kp/zJmAAg4zSXffF7Lpv4VcZhzNKslZoMCKx/g+TUOYkR/6KY+jwkdmxiAbDhDmbbNIyb/Y2AWhX+F9e0iREdK+7DwWTt3wDSM9Xpmm2aEaWiWz1mE8lHGsEh2EXlZptlm6Ff7gaOx3hPyxH9f2MBRNbTmWAtPZj+tyaDw5IRBpfLDwZ0BfZrXEyyGwDZ0ywYtgs9JuT5rv/10cv5Yp6EDPFriUKjDYgzEOnanwemiEtFmOM2pbu7zl5OJrYF+xZ5cqkKg5yVvST+5QoWStEYyqgxrz9Rolh28/0Z3cLPRmIhaP4Bzw368hfIWD4yMvZaTxV4sf9+3ruGs8kmMzCJ1vyXcK0xBrU01o3TyM43eN+DPqfvn6pP4SAmvllIKvpyuBk136Ku4zORJzArfxUAx6jXKG76sW8rB2yj2hS8jQE2HO0w9CdzXJugq8NckKqyD0ao2EFgFEW+gkfw6iiSUVUS6NHdCEBSDI9lbJaxJMoINViyJriI7EBl1pcJ6J10DY55Qn/5oYIyLbFQGlTXOkQNC61pVYTxg=
      on:
        tags: true
